### ISSUE TITLE
Issue running the script, any insights please

### ISSUE THREAD

**Issue by r2079** [yadutaf/tracepkt#5]
ubuntu@azubuntu:~/traceping/tracepkt$ sudo python tracepkt.py 4.2.2.2
cannot attach kprobe, probe entry may not exist
Traceback (most recent call last):
  File "tracepkt.py", line 124, in <module>
    b = BPF(src_file='tracepkt.c')
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 344, in __init__
    self._trace_autoload()
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 1093, in _trace_autoload
    fn_name=fn.name)
  File "/usr/lib/python2.7/dist-packages/bcc/__init__.py", line 648, in attach_kprobe
    (fn_name, event))
Exception: Failed to attach BPF program kprobe__ip6t_do_table to kprobe ip6t_do_table

ubuntu@azubuntu:~/traceping/tracepkt$ uname -a
Linux azubuntu 5.3.0-1020-azure #21~18.04.1-Ubuntu SMP Wed Apr 15 09:35:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@azubuntu:~/traceping/tracepkt$ hostnamectl
   Static hostname: azubuntu
         Icon name: computer-vm
           Chassis: vm
        Machine ID: dd130826d9f84b9589cfe58d2a4860f8
           Boot ID: d9d41daf30e144c796c97ea0938e66df
    Virtualization: microsoft

**Comment by yadutaf** [comment]
It is likely that the kernel symbols changed a bit since the time this was written.
This project is no longer active. I will archive it.
